### ISSUE TITLE
State doesn't change in on or of

### ISSUE THREAD

**Issue by djdjordy** [nstrelow/ha_philips_2016#11]
Since updating the file mediaplayer.py the state of my TV won't change anymore.
Do more people have that issue?

Regards,

Djordy

**Comment by nstrelow** [comment]
The last changes that were made, did not include any changes on the logic on that part.
I can only assume that something else is not working. Al6so the state detection of the TV is not perfect, but should be usable.

Did you include all needed files and update your configuration accordingly?
The component is now named `philips_android_tv` and *not* `philips_201`

**Comment by djdjordy** [comment]
Thanks for you reaction! I found the old python script and set them back,
and now it works.
When I use the new philips_android_tv I will get a warning that I have to
remove the "mac:"
Thanks for your reply!

Op vr 3 mei 2019 om 13:26 schreef Nils Strelow <notifications@github.com>:

**Comment by djdjordy** [comment]
Hi Nils,

Updated the .py again and this messages wil show up.. hope you can help me.

Update for media_player.tv_woonkamer fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 377, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/util/__init__.py", line 224, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/philips_android_tv/media_player.py", line 235, in update
    self._tv.update()
  File "/config/custom_components/philips_android_tv/media_player.py", line 314, in update
    self.getState()
  File "/config/custom_components/philips_android_tv/media_player.py", line 381, in getState
    r = self._getReq('powerstate')
  File "/config/custom_components/philips_android_tv/media_player.py", line 291, in _getReq
    return json.loads(resp.text)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by nstrelow** [comment]
JSON Error mostly is the authentification not working. Try to get a new user + pw.
