### ISSUE TITLE
tv freezes when i start from the power on button.

### ISSUE THREAD

**Issue by jmros** [nstrelow/ha_philips_2016#4]
wen i push the on off button in hass the red ligth disapears but the tv doesn't starts.
the remote control doesnt works

i need to unplug and and plug agin from the wall

**Comment by nstrelow** [comment]
It should take some time, but then start.

Are other commands working when it is already started?

As this is probably specific to your device, I will not be able to fix it. Maybe a future update from Philips will solve your problem

**Comment by jmros** [comment]
https://www.philips.es/c-p/55PUS6432_12/6000-series-televisor-4k-ultraplano-con-tecnologia-android-tv-ambilight-en-2-lados-y-pixel-plus-ultra-hd/caracteristicastecnicas
55PUS6432/12

**Comment by jmros** [comment]
the log shows this.
`2019-02-25 17:36:30 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 239, in async_update_ha_state
    attr = self.state_attributes or {}
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/media_player/__init__.py", line 776, in state_attributes
    in ATTR_TO_PROPERTY if getattr(self, attr) is not None
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/media_player/__init__.py", line 776, in <dictcomp>
    in ATTR_TO_PROPERTY if getattr(self, attr) is not None
  File "/home/homeassistant/.homeassistant/custom_components/philips_2016/media_player.py", line 117, in volume_level
    return self._volume / self._max_volume
TypeError: unsupported operand type(s) for /: 'NoneType' and 'NoneType'
2019-02-25 17:36:33 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 239, in async_update_ha_state
    attr = self.state_attributes or {}
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/media_player/__init__.py", line 776, in state_attributes
    in ATTR_TO_PROPERTY if getattr(self, attr) is not None
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/media_player/__init__.py", line 776, in <dictcomp>
    in ATTR_TO_PROPERTY if getattr(self, attr) is not None
  File "/home/homeassistant/.homeassistant/custom_components/philips_2016/media_player.py", line 117, in volume_level
    return self._volume / self._max_volume
TypeError: unsupported operand type(s) for /: 'NoneType' and 'NoneType'
`

**Comment by denilsonsa** [comment]
I've noticed this behavior on Philips 55PUS6501/12. I haven't had time to investigate what happens.

How to reproduce:

1. If the TV is on, we can press the power button…
    * On the IR remote, and it turns off as expected (the screen goes blank, the red LED turns on).
    * On Home Assistant interface, and it turns off as expected (the screen goes blank, the red LED turns on).
2. Now the TV is off (or in a low-power standby mode). If I press the power button…
    * On the IR remote, it turns on quickly, in a couple of seconds, as expected.
    * On Home Assistant interface, now things get buggy. Apparently, pressing the button does nothing, the TV still looks like it's off.
3. Now the TV is off, but the power button in HA has been pressed. If I press…
    * The power button on the IR remote, the TV looks like it will turn on (the red LED turns off), but nothing happens even after a minute. HA still seems to show it as off. I have unplug it from AC power to hard-reset it.

Worth noting that HA is running on Raspberry Pi, and both HA and the TV are connected to wired ethernet.
