### ISSUE TITLE
Tests mit neuer FAV-Option

### ISSUE THREAD

**Issue by olbjan** [nstrelow/ha_philips_2016#9]
File "/config/custom_components/philips_android_tv/media_player.py", line 45, in <module>
    DEFAULT_FAV = false
NameError: name 'false' is not defined

**Comment by olbjan** [comment]
**
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 377, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/util/__init__.py", line 224, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/philips_android_tv/media_player.py", line 239, in update
    self._tv.update()
  File "/config/custom_components/philips_android_tv/media_player.py", line 320, in update
    if favorite_only:
NameError: name 'favorite_only' is not defined
mit den ' ' um den default started ha wieder und jetzt gibt es obige meldung**

**Comment by nstrelow** [comment]
Should be fixed with the newest commit.

Very bad typos and errors. The real downside of programming without testing.

I will close this issue as soon as someone reports it working.

**Comment by olbjan** [comment]
Funktioniert!
Getestet ohne favorite_channels_only option und mit deroption true.

Danke für deine Arbeit!
